import React, { useEffect, useMemo, useState } from 'react';
import { BriefcaseBusiness, Home, MapPin } from 'lucide-react';
import { MapContainer, TileLayer, GeoJSON, CircleMarker, Popup } from 'react-leaflet';
import type { GeoJsonObject } from 'geojson';
import 'leaflet/dist/leaflet.css';
import { Indicado, IndicacaoEnriquecida } from '../../types';

type ModoMapa = 'residencia' | 'trabalho';
interface Props { indicados: Indicado[]; grade: IndicacaoEnriquecida[]; onOpenFichaIndicado: (id: string) => void; onOpenNovaIndicacaoParaIndicado: (id: string) => void; }
const normalizar = (v?: string) => v?.trim() || 'Não informado';
const oficial = 'https://mapas.fortaleza.ce.gov.br/api/download/geojson/21';
const centro: [number, number] = [-3.7319, -38.5267];

export const MapaBairrosView: React.FC<Props> = ({ indicados, grade, onOpenFichaIndicado }) => {
  const [modo, setModo] = useState<ModoMapa>('residencia');
  const [geojson, setGeojson] = useState<GeoJsonObject | null>(null);
  useEffect(() => { fetch(oficial).then(r => r.json()).then(setGeojson).catch(() => setGeojson(null)); }, []);
  const pontos = useMemo(() => { const grupos = new Map<string, Indicado[]>(); indicados.forEach(p => { const i = grade.find(x => x.indicado_id === p.id && x.status === 'Ativo'); const cidade = i?.local.cidade_trabalho || (i?.local.esfera === 'Municipal - Fortaleza' ? 'Fortaleza' : undefined); const nome = modo === 'residencia' ? (p.cidade.toLowerCase() === 'fortaleza' ? normalizar(p.bairro_residencia) : normalizar(p.cidade)) : (cidade?.toLowerCase() === 'fortaleza' ? normalizar(i?.local.bairro_trabalho) : normalizar(cidade || i?.local.nome_empresa_ou_orgao)); grupos.set(nome, [...(grupos.get(nome) || []), p]); }); return [...grupos.entries()].map(([nome, pessoas]) => ({ nome, pessoas, quantidade: pessoas.length })); }, [indicados, grade, modo]);
  const porNome = new Map(pontos.map(p => [p.nome.toLowerCase(), p]));
  const estilo = (feature?: any) => { const nome = String(feature?.properties?.Nome || feature?.properties?.nome || feature?.properties?.NOME || ''); const p = porNome.get(nome.toLowerCase()); const max = Math.max(...pontos.map(x => x.quantidade), 1); return { color: '#38bdf8', weight: 1, fillColor: '#0284c7', fillOpacity: p ? .25 + (p.quantidade / max) * .65 : .08 }; };
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-brand-400"><MapPin className="h-4 w-4" /><span className="text-[11px] font-bold uppercase tracking-wider">Mapa territorial</span></div><h2 className="text-xl font-black text-white mt-1">Cobertura das pessoas indicadas</h2><p className="text-xs text-slate-400 mt-1">Fortaleza por bairro e demais municípios por cidade.</p></div><div className="flex rounded-xl border border-slate-800 bg-slate-900 p-1"><button type="button" onClick={() => setModo('residencia')} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold ${modo === 'residencia' ? 'bg-brand-600 text-white' : 'text-slate-400'}`}><Home className="h-3.5 w-3.5" /> Onde moram</button><button type="button" onClick={() => setModo('trabalho')} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold ${modo === 'trabalho' ? 'bg-brand-600 text-white' : 'text-slate-400'}`}><BriefcaseBusiness className="h-3.5 w-3.5" /> Onde trabalham</button></div></div><div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><MapContainer center={centro} zoom={11} scrollWheelZoom className="h-[560px] w-full"><TileLayer attribution="&copy; OpenStreetMap" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{geojson && <GeoJSON data={geojson} style={estilo} onEachFeature={(f, l) => { const nome = String(f.properties?.Nome || f.properties?.nome || f.properties?.NOME || 'Bairro'); l.bindPopup(`${nome}<br>${porNome.get(nome.toLowerCase())?.quantidade || 0} pessoa(s)`); }} />}{pontos.filter(p => !p.nome.toLowerCase().includes('não informado')).map(p => <CircleMarker key={p.nome} center={centro} radius={Math.min(28, 8 + p.quantidade * 3)} pathOptions={{ color: '#f59e0b', fillColor: '#f59e0b', fillOpacity: .7 }}><Popup><strong>{p.nome}</strong><br />{p.quantidade} pessoa(s)</Popup></CircleMarker>)}</MapContainer></div><p className="text-[11px] text-slate-500">Clique em um bairro para ver a concentração. O mapa usa dados agregados e não mostra endereços.</p><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{pontos.sort((a,b) => b.quantidade-a.quantidade).map(p => <button key={p.nome} type="button" onClick={() => p.pessoas[0] && onOpenFichaIndicado(p.pessoas[0].id)} className="rounded-xl border border-slate-800 bg-slate-900 p-3 text-left hover:border-brand-500"><span className="block text-xs font-bold text-white">{p.nome}</span><span className="text-[10px] text-brand-300">{p.quantidade} pessoa(s)</span></button>)}</div></div>;
};
